from pydantic import BaseModel, Field, validator, field_validator
from typing import Optional
from bson.objectid import ObjectId


class DataChunk(BaseModel):
    id: Optional[ObjectId] = Field(
        None, alias="_id"
    )  # "_id"=> private ,can't access it directly so we will solve it by alias topic وNone =>optional because when we create a new chunk we don't have the id yet, it will be generated by MongoDB
    chunk_text: str = Field(
        ..., min_length=1
    )  # "..." => required field, min_length => ensure that the chunk text is not empty
    chunk_metadata: dict
    chunk_order: int = Field(..., gt=0)  # Ensure chunk_order is a non-negative integer
    chunk_project_id: ObjectId

    class Config:
        arbitrary_types_allowed = True

    @classmethod
    def get_indexes(cls):
        return [
            {
                "key": [("chunk_project_id", 1)],
                "name": "chunk_project_id_index_1",
                "unique": False,
            }
        ]
