"""adding new column in project table

Revision ID: 85249b592edb
Revises: 86f0293c4e53
Create Date: 2026-04-23 15:40:36.723524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85249b592edb'
down_revision: Union[str, Sequence[str], None] = '86f0293c4e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('new_dumy_col', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'new_dumy_col')
    # ### end Alembic commands ###
